### ISSUE TITLE
More than one SYCL device supported?

### ISSUE THREAD

**Issue by xangma** [benoitsteiner/tensorflow-opencl#68]
Hi all,

Looking to see if more than one SYCL is possible at the moment. I can see that the sycl device factory adds them incrementally upon building tensorflow-opencl from source, but the physical_device_desc: "device: 0, name SYCL, pci bus id: 0" is hardcoded in, which makes me think only one SYCL device is currently supported.

All my gpus show up in computecpp_info fine, and clinfo.

Does anyone know?

Thanks!

### Environment info
Operating System: Ubuntu 14.04
Computecpp version: 0.1.4

**Comment by rodburns** [comment]
The most up to date branch to use is here https://github.com/lukeiwanski/tensorflow-opencl.git with changes being pushed to the main TensorFlow branch. I believe what you are seeing is fixed in that branch. The latest Pull Request for getting the latest to the main branch is here https://github.com/tensorflow/tensorflow/pull/9117

**Comment by xangma** [comment]
Thanks for your response. Doesn't seem to be fixed yet. I compiled the pull request changes and SYCL:1 is still not showing up sadly.

**Comment by rodburns** [comment]
We've updated the documentation now and there is a new branch that we believe will work for you. See here https://www.codeplay.com/products/computesuite/computecpp/guides/how-to-setup-tensorflow-with-computecpp
We are propagating the changes to the main TensorFlow repository at the moment.
